### ISSUE TITLE
DoubleTab and zoom 

### ISSUE THREAD

**Issue by yooni126** [fljot/Gestouch#101]
Hi
i have a large image .
so can u tell me how can i zoom in custom point (increase scale) with double tab?

_doubleTapGesture = new TapGesture(_container);
_doubleTapGesture.numTapsRequired = 2;
_doubleTapGesture.addEventListener(GestureEvent.GESTURE_RECOGNIZED, onGestureTap);
_zoom = new TransformGesture(_container);
private function onGestureTap(e:GestureEvent):void
		{
			var matrix:Matrix = _container.transformationMatrix;
			var gestureTab:TapGesture = e.target as TapGesture;
			
			if (gestureTab == _doubleTapGesture)
			{
				???????????
			}
		
		}

**Comment by fljot** [comment]
[Gesture#location](https://github.com/fljot/Gestouch/blob/master/src/org/gestouch/gestures/Gesture.as#L210) will give you point (in global coordinate space) of your tap, so you can scale it around that point:
```
scaleAroundGlobalPoint(_container, gesture.location, /*scale:*/ 2);

function scaleAroundGlobalPoint(obj:DisplayObject, point:Point, scale:Number):void
{
    const matrix:Matrix = obj.transform.matrix;
    const transformPoint:Point = matrix.transformPoint(obj.globalToLocal(point));
    matrix.translate(-transformPoint.x, -transformPoint.y);
    matrix.scale(scale, scale);
    matrix.translate(transformPoint.x, transformPoint.y);

    obj.transform.matrix = matrix;
}
```

**Comment by yooni126** [comment]
Great, thank you for the response. 
its perfect but how can i tween it?
I'm using TweenMax but when i write this code my object doesn't scale!
TweenMax.to(obj, 0.25, {transformationMatrix: matrix, ease: Linear.easeOut});

**Comment by fljot** [comment]
http://lmgtfy.com/?q=tweenmax+scale+around+point
2nd link
._.
