### ISSUE TITLE
Gestouch suddenly stopped working on Windows 10 with latest Animate CC

### ISSUE THREAD

**Issue by stefanedberg** [fljot/Gestouch#103]
I have an AIR application that has been running Gestouch for a couple of years. I've been updating it regularly and now Gestouch events stopped working on Windows 10 after updating to the latest Animate CC release. They work as expected on Mac.

I've also tried running the source code in Animate CC on the Windows machine but the event just doesn't fire. Other events like MOUSE_DOWN and CLICK works.

Have any tricks up your sleeve?

Edit:

It's more specifically the TransformGestureEvent.GESTURE_TRANSFORM and PanGestureEvent.GESTURE_PAN events that stops firing.

Seems to have something to do with the multi-touch drivers from PQLabs (multitouch.com). Uninstalled them, rebooted and it works. Worked with the drivers installed a couple of days ago. Wierd. Have to investigate further.

**Comment by fljot** [comment]
@stefanedberg mhm perhaps some logs will help you understand what's happening
Check if this makes sense to you https://github.com/fljot/Gestouch/commit/7d929b23b6482e2448ef18ab412d27fae4c2a325 (I remember adding logging in `develop` branch https://github.com/fljot/Gestouch/tree/develop)

**Comment by fljot** [comment]
Closing for now. Please feel free to update and reopen.
