### ISSUE TITLE
Can GesTouch used in Flash Professional?

### ISSUE THREAD

**Issue by pizzayap** [fljot/Gestouch#12]
Hi,

Can GesTouch used in Flash Professional?
I've go through all the example and it is all in Flex.

Sorry for I'm a beginner to implement Flex to Flash.
Can I have the sample how to code in Flash? I'm using GesTouch in my old projects.

Thanks!

**Comment by fljot** [comment]
Yes, you can use it with pure AS3 projects compiled with Flash Professional.
https://github.com/fljot/Gestouch/issues/6
