### ISSUE TITLE
org.gestouch.events ? v0.4.1

### ISSUE THREAD

**Issue by retropunk** [fljot/Gestouch#14]
Hello, I am looking to try out your library but I can't get this version working with the examples. org.gestouch.events had many classes deleted.
Any help would be great!
Thanks!

**Comment by fljot** [comment]
Oh I will update examples as soon as I get to MY computer. Well basically (as you should see in readme) I removed gesture–specific events and those values are stored in the gesture itself. I also changed state change events to be more generic and independent and so performant.

**Comment by retropunk** [comment]
oh I see. Well the examples still work with the previous swc version. 
I didn't see the comments that talked about that. Sounds like a great idea! Thanks!

**Comment by fljot** [comment]
pushed
