### ISSUE TITLE
swipe example?

### ISSUE THREAD

**Issue by CoIin** [fljot/Gestouch#16]
I have seen example code for setting a display object for a SwipeGesture instance, but I can't find any example code that shows what listeners you would add, and how the listener function would look. Are there any examples online for using Gestouch for handling swipes?

**Comment by CoIin** [comment]
For anyone who chanced across this, I found that listening for GestureEvent.GESTURE_RECOGNIZED, and then looking at the event.target.offsetX would let me known when to do left and right swipes.

**Comment by fljot** [comment]
Well it's actually all here https://github.com/fljot/GestouchExamples/blob/master/src/org/gestouch/examples/views/SwipeGestureView.mxml

For more precise (and maybe even performant) usage I'd recommend you to set desired direction first

``` as
var swipe:SwipeGesture = ...
swipe.direction = SwipeGestureDirection.HORIZONTAL;
// which is just a shortcut to:
swipe.direction = SwipeGestureDirection.RIGHT | SwipeGestureDirection.LEFT
```

Later it handler you can get offsets via

``` as
// var swipe:SwipeGesture = event.target as SwipeGesture;// if you don't have a reference to gesture instance
trace(swipe.offsetX, swipe.offsetY);
```

**Comment by CoIin** [comment]
Thanks for the pointer. I had misunderstood the github list at this page:

https://github.com/fljot/GestouchExamples/tree/master/src/org/gestouch/examples

I thought it was a list of the contents of the zip you would download, when really it's a directory listing.

**Comment by fljot** [comment]
There more examples, including some pretty advanced ones. Recommend do build and install on a mobile device and inspect code carefully.

**Comment by CoIin** [comment]
I'm doing quite well with Gestouch, including using the transformgesture for rotating resizing and panning an image all in one go. Some of your examples are a lot more complicated than need be, plus you develop for Flex, which is a bit like an alien language to some of us Flash Pro users!

**Comment by fljot** [comment]
Well.. those examples show the **must-know** API. So I wouldn't call that "more complicated than need be".

And I don't develop for Flex. I'm just using Flex for examples UI shell. Most of the actual gestures-related code I did in AS3 specifically (there's only one example that uses MXML-syntax, that shows that you can easily use declarative MXML for gestures also).
