### ISSUE TITLE
Compiling from flash professional

### ISSUE THREAD

**Issue by dsaisho** [fljot/Gestouch#21]
Hello, I linked your swc and am trying to do a very simple swipe example and am not able to pick up the recognized event. I do not get error when I compile and my code looks like this:

import org.gestouch.gestures.SwipeGesture;
import org.gestouch.events.GestureEvent;
import flash.text.TextField;

var swiper:SwipeGesture = new SwipeGesture(swipe);

var tf:TextField = new TextField();
tf.width = 500;
tf.height = 100;
tf.text = 'something';
addChild(tf);

swiper.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onGesture);

function onGesture(event:org.gestouch.events.GestureEvent):void{

```
var ges:SwipeGesture = event.target as SwipeGesture;
tf.text = new String(ges.offsetX+' '+ges.offsetY);
```

}

DO I need to set any type of input mode?

thank you.

**Comment by dsaisho** [comment]
Problem is solved, I just tested on a touch enabled device and it worked very nice. However it was not working in Device Central and thats when I wrote my first message. 

Thanks for the great lib

**Comment by fljot** [comment]
Probably you was just swiping too slow with mouse in Device Central.

**Comment by dsaisho** [comment]
I was doing the same swipe that was working with adobes TransformGestureEvent. However when I was testing your the gestouch lib in device central it was just with the swf, so not packaged by air. Do you think that's what could make the difference? when I tested on my touch enabled device when it worked it was with air. 

But man, this lib was a life saver. Windows doesnt support Swipe Gesture, so your lib saved the day. Thanks again.

**Comment by fljot** [comment]
Eehm.. there's absolutely nothing to do with `flash.events.TransformGestureEvent` so I'm not sure I understand your Device Central thing.
Gestouch by default tries to decide itself whether to handle MouseEvent-s or TouchEvent-s and doesn't require AIR as far as I remember.

**Comment by dsaisho** [comment]
uh im just saying I did the same swipe motion with my hand using your lib and default adobe lib in device central. your lib didnt detect, adobe lib did.

**Comment by Cyberben3d** [comment]
I had the same experience. When you run the movie from Flash [CTRL+ENTER] it gives you a touch screen simulator which works with native AS3 touch gestures but not Gestouch. I thought I was doing something wrong until I read this post and realized I had to publish to my iPad to get Gestouch to work. Got it now :)
