### ISSUE TITLE
Feathers support

### ISSUE THREAD

**Issue by AlBirdie** [fljot/Gestouch#28]
Are there any plans to adapt Gestouch to work with the current version of Feathers?
I'd love to use this library with Feathers as it worked great with my Flex projects.

I've seen the Starling support, but that does seem outdated by now.

**Comment by fljot** [comment]
Why outdated? No, it supports Starling out-of-the-box and can support other libraries such as ND2D, Away3D and others.

**Comment by AlBirdie** [comment]
Maybe outdated wasn't the right word. 
I've tried your Starling usage example in my Feathers project and step 2 already throws an error:

Multiple markers at this line:
-starling
-Access of possibly undefined property starling.
-Access of possibly undefined property starling.

Not sure if something has changed with the current 1.2 Starling and 1.0 Feathers releases, or if I'm doing something wrong here.

**Comment by osro** [comment]
@AlBirdie 

"The latest version of Feathers requires Starling Framework 1.3, which hasn't been officially released yet, but you can download the latest Starling source code from Github."

So, if you want to use the latest Feathers, you need to build the Starling from the source code.

**Comment by AlBirdie** [comment]
Sorry, meant to write Starling 1.3, so the error I'm getting with Gestouch remains.

**Comment by fljot** [comment]
@AlBirdie are you sure you have Starling "connected" to your project (via swc or sources)? Or have they changed some packages-namespaces?

**Comment by AlBirdie** [comment]
Yes, the project is set up properly. Not sure if they changed packages/namespaces.
Actually, I accidentally gave the wrong error above, should have been this one instead;

-Access of possibly undefined property display through a reference with static type Starling.
-Call to a possibly undefined method StarlingDisplayListAdapter.

**Comment by AlBirdie** [comment]
Call me stupid. Totally missed to import starling.display.DisplayObject. D'oh!
Works flawless now.

**Comment by fljot** [comment]
This is totally ok and I understand that... wait, NO! That's IDE's job to write imports, why would you even think about them!

**Comment by AlBirdie** [comment]
My thoughts exactly, but FB 4.7 has some serious flaws, not handling imports correctly is a minor issue, though. ;)
Anyway, thanks for your help! Appreciate your effort for this great library.
