### ISSUE TITLE
problem with reactivating swipe event

### ISSUE THREAD

**Issue by swwol** [fljot/Gestouch#29]
Hi there,

 I am having an issue where if I have a swipe event added to an object on the stage, and then I addChild another MovieClip on top of the object that has the swipe event, when I remove the object on top,  the swipe event no longer fires.

This is the case even if I remove and then replace the event listeners, or even remove and replace the entire object

Could you perhaps explain best way to add and remove the swipe event listener from the bottom layer object so that it can be activated/deactivated?

many thanks!

**Comment by fljot** [comment]
A simple project maybe?

**Comment by swwol** [comment]
Thanks Pavel, I've solved it now - the problem was caused by a line of code
I'd forgotten about in the added object that changed the touchmode. Now
thats gone its all working fine.

Many thanks for making this code available, its proving really useful!

Sam.

On 16 December 2012 10:54, Pavel Pevnitskiy notifications@github.comwrote:

> A simple project maybe?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/fljot/Gestouch/issues/29#issuecomment-11416472.

## 

Sam Woolf
www.samwoolf.net
07753573585
