### ISSUE TITLE
TapGesture event location

### ISSUE THREAD

**Issue by madsleejensen** [fljot/Gestouch#3]
I both the alpha 0.3.1 and 0.4 the im having problems receiving the X/Y coordinate of the tap. The other gestures works fine :)

TapGestureEvent.stageX / Y always returns NaN.
TapGestureEvent.localX / Y always returns NaN.

**Comment by fljot** [comment]
Thanks! Fixed.
I decided not to bump version and create release commit and swc yet. So check out "develop".

*damn.. I wonder how to connect issues with actual commits

**Comment by madsleejensen** [comment]
Wow quick fix! :) Gonna have to edit the files myself but i can see the changes are quite small, but i the develop branch does not support Starling right ? Thanks for the help :)

**Comment by fljot** [comment]
Yea, current Starling-supported branch is behind develop.. So you can just rebase your local starling branch if you want (to have those two last fixes). I'll finally close this issue once fixes go into develop or master.
