### ISSUE TITLE
Problem panning on iPad 4

### ISSUE THREAD

**Issue by treylok** [fljot/Gestouch#30]
Hi, I am having a problem with panning on the iPad 4.  When I drag an object it does not stay centered on my finger and it strays quite noticeably.  For instance, if an object is at the top of the screen, I click it and drag going downward, by the time I get a little more than 1/2 way down the screen with my finger, the object I am dragging is at the bottom of the screen.  Everything work fine on the desktop when I test with a  mouse  and on an android tablet I have.  It seems to only be present on the iPad 4.  Could it have something to do with the retina display or something with my code?   Thanks for any help.

Here is a simple test example:

```
<?xml version="1.0" encoding="utf-8"?>
<s:View xmlns:fx="http://ns.adobe.com/mxml/2009" 
        xmlns:s="library://ns.adobe.com/flex/spark" title="TestDrag" creationComplete="init()">
    <fx:Declarations>
        <!-- Place non-visual elements (e.g., services, value objects) here -->
    </fx:Declarations>
    <fx:Script>
        <![CDATA[
            import org.gestouch.events.GestureEvent;
            import org.gestouch.gestures.TransformGesture;

            protected function init():void{
                var transformGesture:TransformGesture = new TransformGesture(box);
                transformGesture.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onRectGesture);
                transformGesture.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onRectGesture);
            }

            private function onRectGesture(event:org.gestouch.events.GestureEvent):void
            {
                const gesture:TransformGesture = event.target as TransformGesture;
                var gestureTarget:Button = gesture.target as Button;
                var matrix:Matrix = gestureTarget.transform.matrix;

                // Panning
                matrix.translate(gesture.offsetX, gesture.offsetY);
                gestureTarget.transform.matrix = matrix;
            }
        ]]>
    </fx:Script>
    <s:Button id="box" label="DRAG ME" width = "150" height = "150" />

</s:View>
```

**Comment by fljot** [comment]
Well it sounds like it's related to retina. What's the size of your view and what's the size of the stage? Maybe view is scaled twice in terms of width and height? If so you need to transform offsets (using view.globalToLocal).

**Comment by treylok** [comment]
Thanks a lot for your response and help.  Unfortunately, I am not that good with matrix operations or positioning in general when it comes to different devices and DPIs.  I tried changing the code by adding

```
var globalPoint:Point =   globalToLocal(new Point(gesture.offsetX, gesture.offsetY));
matrix.translate(globalPoint.x, globalPoint.y);
```

but I am still not getting the correct results.  I did however notice when I change the application DPI from 160 to 240 everything works as expected on the retna display.

Here is the info I am getting for the stage and view dimensions:
Stage: 1536 x 2008
View:  1024 x 1293.66

Thanks again, sorry if this post does not belong here because I think it is an issue on my end and not with your code.

**Comment by fljot** [comment]
Well it's a common task, and I should actually add it to examples project.
Haven't tested, but I think it should work:

```
public static const ZERO_POINT:Point = new Point();// define somewhere

private var globalOffset:Point = new Point();//reuse same instance for better performance
globalOffset.x = gesture.offsetX;
globalOffset.y = gesture.offsetY;
var offsetInThis:Point = this.globalToLocal(globalOffset).subtract(this.globalToLocal(ZERO_POINT));
```

**upd:** I would include this functionality in gestures of course, BUT since architecture is not only about flash.display::DisplatObject anymore... This is not that hard to transform stuff after all.

**Comment by treylok** [comment]
It is working like a charm!  Thanks a ton, both for your help with my problem and for your great work on this library and providing them to us for use!
