### ISSUE TITLE
TapGesture maxTapDelay

### ISSUE THREAD

**Issue by sidesixmedia** [fljot/Gestouch#31]
Hi fljot, 

We don't see a difference in gesture recognition timing when we change the tap.maxTapDelay value. Shouldn't this alter the timer duration associated with the TouchEnd detection of the TapGesture class or is that not its intended purpose?

We're still working from the slop-hotfix branch you created a few weeks back.

Thank you!

**Comment by fljot** [comment]
`maxTapDelay` is the max delay between taps (for multi-taps such as double-tap when `numTapsRequired = 2`). Are you using this property for that purpose?

**Comment by sidesixmedia** [comment]
Ah, then no. We thought it was a duration to adjust how long the user has to make a complete Tap gesture (start touch time + end touch time < maxTapDelay). Didn't realize it is for multi-touch scenarios.

So there isn't a way to alter the gesture recognition time for Taps?

**Comment by fljot** [comment]
`maxTapDuration` (in ms, default is 1500)

And why do you want to change that? This is the value they have on iOS and I think they chose it for a reason =)

**Comment by sidesixmedia** [comment]
Because one size rarely fits all =)
We don't have specific need to change the default, but thought there would be an option to do so since some of the other gestures support altering times and/or velocities. Consider this issue closed!

**Comment by fljot** [comment]
And that's why I left it public, possible to change =)
