### ISSUE TITLE
GestureState.Failed happening "randomly" during TransformGestures

### ISSUE THREAD

**Issue by zenrobin** [fljot/Gestouch#33]
Hi!

I'm using the TransformGesture, and when I click-drag-release a lot in succession, at some point I'll get a GestureState == FAIL.

The visual result:  the object moves---moves---moves--- and then MISS!  The mouse moves, but the object doesn't (cause the gesture failed).

Is there a way I can print out what the failure is in order to troubleshoot what is happening?  It's very random - I can't quite understand why it's failing.

Sometimes, once I miss a click, I can keep doing the same translation with my mouse and keep getting the failure again and again. But the second I vary the timing or movement, it picks it up again and starts working.

Any ideas on how to solve or troubleshoot would be greatly appreciated. 

Thanks!

**Comment by fljot** [comment]
First of all let's ensure we're talking about the same version, so go and grab the sources from this commit
https://github.com/fljot/Gestouch/commit/4398712f0c5b704818457bf120193157bd09dfdb

**Comment by zenrobin** [comment]
Thanks for the quick reply!

I switched from the swc to the latest src, and then merged in your two changes from 4398712.

Sadly, I still see fail states. Here is how I'm detecting them:

```
    public function onSCMouseMove(event:GestureEvent):void {
        trace("[SceneStage] onSCMouseMove:", event.oldState + "->" + event.newState);
        if (event.oldState == GestureState.FAILED)
        {
            trace("[SceneStage] onSCMouseMove() - Gesture state: FAIL");  
        }
```

Some output:

[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.ENDED
[SceneStage] onSCMouseMove: GestureState.ENDED->GestureState.IDLE
[SceneStage] onSCMouseMove: GestureState.IDLE->GestureState.POSSIBLE
[SceneStage] onSCMouseMove: GestureState.POSSIBLE->GestureState.BEGAN
[SceneStage] onSCMouseMove: GestureState.BEGAN->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.ENDED
[SceneStage] onSCMouseMove: GestureState.ENDED->GestureState.IDLE
[SceneStage] onSCMouseMove: GestureState.IDLE->GestureState.POSSIBLE
[SceneStage] onSCMouseMove: GestureState.POSSIBLE->GestureState.FAILED
[SceneStage] onSCMouseMove: GestureState.FAILED->GestureState.IDLE
[SceneStage] onSCMouseMove() - Gesture state: FAIL

**Comment by fljot** [comment]
Check the project settings again because there's no more IDLE anymore.
https://github.com/fljot/Gestouch/blob/4398712f0c5b704818457bf120193157bd09dfdb/src/org/gestouch/core/GestureState.as

**Comment by fljot** [comment]
So, with the recent version, show me the stacktrace once it fails:

```
if (event.newState == GestureState.FAILED)
{
    trace("failed:", (new Error()).getStackTrace());
}
```

and did I get you right — it fails **while** you're moving?

**Comment by zenrobin** [comment]
Found the "develop" branch and I'm now using that -- master still has idle for me for some reason. 

Also found that I needed to convert to GESTURE_RECOGNIZED in a few cases where I was using something else. Seems like you cleaned some things up, and I wasn't getting a location coordinate for the event state I was previously using. 

Onward:
Here is the behavior I'm using to repro: 

click -> release  // (to select an object to transform)
clickhold ->drag ->release // moves an object
clickhold ->drag ->release  // move here
clickhold ->drag ->release  // move there
clickhold ->drag ->release  // move somewhere else
clickhold ->drag  // FAIL

The fail happens before the move -- the object stays put / the cursor moves without it.

Here's the latest trace with your code:

[SceneStage] onSCMouseMove: GestureState.POSSIBLE->GestureState.BEGAN
[SceneStage] onSCMouseMove: GestureState.BEGAN->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.ENDED
[SceneStage] onSCMouseMove: GestureState.ENDED->GestureState.POSSIBLE
[SceneStage] onSCMouseMove: GestureState.POSSIBLE->GestureState.BEGAN
[SceneStage] onSCMouseMove: GestureState.BEGAN->GestureState.CHANGED
[SceneStage] onSCMouseMove: GestureState.CHANGED->GestureState.ENDED
[SceneStage] onSCMouseMove: GestureState.ENDED->GestureState.POSSIBLE
[SceneStage] onSCMouseMove: GestureState.POSSIBLE->GestureState.FAILED
failed: Error
    at com.storytime.creator::SceneStage/onSCMouseMove()[client\src\com\storytime\creator\SceneStage.as:745]
    at flash.events::EventDispatcher/dispatchEventFunction()
    at flash.events::EventDispatcher/dispatchEvent()
    at org.gestouch.gestures::Gesture/setState()[client\src\org\gestouch\gestures\Gesture.as:577]
    at org.gestouch.gestures::Gesture/org.gestouch.core::gestouch_internal::setState_internal()[client\src\org\gestouch\gestures\Gesture.as:598]
    at org.gestouch.core::GesturesManager/org.gestouch.core::gestouch_internal::onGestureRecognized()[client\src\org\gestouch\core\GesturesManager.as:186]
    at org.gestouch.gestures::Gesture/setState()[client\src\org\gestouch\gestures\Gesture.as:589]
    at org.gestouch.gestures::SwipeGesture/onTouchMove()[client\src\org\gestouch\gestures\SwipeGesture.as:241]
    at org.gestouch.gestures::Gesture/org.gestouch.core::gestouch_internal::touchMoveHandler()[client\src\org\gestouch\gestures\Gesture.as:657]
    at org.gestouch.core::GesturesManager/org.gestouch.core::gestouch_internal::onTouchMove()[client\src\org\gestouch\core\GesturesManager.as:284]
    at org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchMove()[client\src\org\gestouch\core\TouchesManager.as:170]
    at org.gestouch.input::NativeInputAdapter/mouseMoveHandler()[client\src\org\gestouch\input\NativeInputAdapter.as:205]
[SceneStage] onSCMouseMove: GestureState.FAILED->GestureState.POSSIBLE
[SceneStage] onSCMouseMove: GestureState.POSSIBLE->GestureState.BEGAN

While still seemingly random, the fail state happens quite easily in my case.  I'd be happy to skype-screen-share with you to show you first hand if that helps.

Thanks for your support.  :)

**Comment by fljot** [comment]
Well the log says that:
1. First you stop TransformGesture (dragging) via releasing the touch.
2. Then you attempt to do it (pan/transform) again, but another gesture (Swipe) is recognized therefore your TransformGesture fails.

my skype is `fljot_`

**Comment by zenrobin** [comment]
Ugh - good call.  I had a swipe gesture in there from an old test that was interfering.   Thanks so much for helping to troubleshoot that.

Question - should I go back to the gestouch swc I was using, or do you think it's best to stay with the dev branch?

**Comment by fljot** [comment]
I'd say this commit from develop branch has nothing experimental and I should actually make a release out of it or maybe a bit later.. so I'd say go with it.

But for me it's still a bit unclear how would swipe be recognized first.. only if it was deeper than transform?

**Comment by zenrobin** [comment]
Yes - swipe was initialized after the transform was initialized.  Is it more standard to do it before?

I think I'm having a similar issue with double-tap -- the transform is listened to first, so it makes it more difficult to successfully make a double-tap happen.  

Thanks again for your support here.

**Comment by fljot** [comment]
Transform and double-tap should not conflict due to different nature — you don't move your finger (much) when tapping. Well you have my skype.. because it sounds a bit weird what you say)

**Comment by zenrobin** [comment]
It's pretty sensitive on my ipad3 -- difficult to get my double-tap context menu to show without moving the object via the Transform Gesture.  I was thinking about doing some "this cancels that" logic, but I'm not at that point yet.   I added you on skype -- would be happy to show you the repro :)
