### ISSUE TITLE
gestures sometimes don't happen

### ISSUE THREAD

**Issue by CoIin** [fljot/Gestouch#36]
I am finding that about half of the time gestures don't trigger. I want to show a simple test case, but my test code doesn't generate any gestures at all. Before I describe how to reproduce the real issue, can you see why this timeline code would not show any gesture events? 'mc' is a movieclip that covers the whole stage:

import org.gestouch.gestures.TransformGesture;
import org.gestouch.gestures.SwipeGesture;
import org.gestouch.events.GestureEvent;
import org.gestouch.core.Gestouch;
import org.gestouch.core.GesturesManager;
import flash.utils.getTimer;

var freeTransform:TransformGesture = new TransformGesture(mc);
freeTransform.addEventListener("began",onFreeTransformBegan);

function onFreeTransformBegan(event:GestureEvent):void {
    trace("began",getTimer(),Gestouch.touchesManager.activeTouchesCount);
}

The 'trace' never happens.

**Comment by fljot** [comment]
Well there are no "began" events generated at all. I think you meant addEventListener(GestureEvent.GESTURE_BEGAN, ...

**Comment by CoIin** [comment]
Yes, in my real thing I use GestureEvent.GESTURE_BEGAN, but as timeline code it didn't compile. I should have check the GestureEvent file to see that the string was "gestureBegan". That works fine.

My simple test case doesn't show the problem, so I need to dig deeper to find what it takes to fail. I'll report back.

**Comment by fljot** [comment]
On the timeline or in mxml you probably need to write the full thing `org.gestouch.events.GestureEvent` because native `flash.events.GestureEvent` somehow has more priority even though you don't import that.

**Comment by fljot** [comment]
@CoIin any progress?

**Comment by CoIin** [comment]
Hey, thanks for checking how I'm doing. One of the things I was doing at the time was urgent, and I worked around the issue by speeding up a transition. I would only run into a problem if the user tried to do more than four swipes within one second, and those were acceptable odds. The other thing I was doing was both pushed back and its requirements changed. To the point that I may not need gestouch at all.

A variation of that second thing will resurface some day, but not just yet. Still, I'll try to find time to look at the issue again. Might as well figure it out now rather than when it's urgent again!

Thanks again for checking in.

**Comment by fljot** [comment]
Closing it for now.
