### ISSUE TITLE
Detect tap anywhere else

### ISSUE THREAD

**Issue by Vic0429** [fljot/Gestouch#37]
How can I detect if user taps any part of the display but not the target object of tap?

**Comment by fljot** [comment]
Well you could set TapGesture on stage and in handler make `gesture.location + hittest` or `gesture.target + contains()` with your object. Same as how you would do it with Mouse.CLICK basically.

**Comment by fljot** [comment]
@Vic0429 did everything work well?

**Comment by Vic0429** [comment]
Yes, it worked well, but later I realized my problem is more difficult...

**Comment by fljot** [comment]
Can I help somehow if Gestouch related?

**Comment by Vic0429** [comment]
Thanks but it's not related to Gestouch.
