### ISSUE TITLE
I want to using Gestouch on Flash CS6

### ISSUE THREAD

**Issue by scofield42** [fljot/Gestouch#38]
I add the codes. Program dont show error. But it dosnt work. Everything is ok but doent work

```
import org.gestouch.events.GestureEvent;
import org.gestouch.gestures.ZoomGesture;

var zoom:ZoomGesture;

zoom = new ZoomGesture(image);
zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onGesture);
zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onGesture);

function onGesture(event:org.gestouch.events.GestureEvent):void {
    const gesture:ZoomGesture = event.target as ZoomGesture;
    trace("Deneme");
    var matrix:Matrix = image.transform.matrix;
    var transformPoint:Point = matrix.transformPoint(image.globalToLocal(zoom.location));
    matrix.translate(-transformPoint.x, -transformPoint.y);
    matrix.scale(gesture.scaleX, gesture.scaleY);
    matrix.translate(transformPoint.x, transformPoint.y);
    image.transform.matrix = matrix;
}
```

**Comment by fljot** [comment]
I hope you're not testing it via some CS6 mobile simulator?

**Comment by scofield42** [comment]
I'm an idiot. I have not tried the phone. Thank you very, very much.

**Comment by fljot** [comment]
... because their gestures simulator is for their gestures only.

**Comment by gokselfikir** [comment]
Hi, I managed to run the above code, but I can not run them, Can you help please?

import org.gestouch.core.Touch;
import org.gestouch.events.GestureEvent;
import org.gestouch.gestures.Gesture;
import org.gestouch.gestures.PanGesture;

var pan:PanGesture = new PanGesture(mySprite);
pan.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onPan);
pan.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onPan);

function onPan(event:org.gestouch.events.GestureEvent):void{
    const gesture:PanGesture = event.target as PanGesture;
    mySprite.move(mySprite.x + gesture.offsetX, mySprite.y + gesture.offsetY);
}

I want to pan with one finger...Please help me.

**Comment by fljot** [comment]
@gokselfikir what is the problem exactly?
