### ISSUE TITLE
resetNotificationProperties bug in ZoomGesture

### ISSUE THREAD

**Issue by eternauta1337** [fljot/Gestouch#41]
It appeares that the line
_scaleX = _scaleY = 1;
in resetNotificationProperties() in ZoomGesture causes the scale values of the gesture to always be 1 or near 1. Commenting this line out allows me to use the gesture. Might require a little review.

**Comment by fljot** [comment]
That's intended behavior. Same for PanGesture `_offsetX = _offsetY = 0;` and others. You grab the deltas in handler and transform your stuff according to them, then they are reset for the next "tick". Take a look at the examples.
