### ISSUE TITLE
[Question]How to get touchId used by swipe gesture?

### ISSUE THREAD

**Issue by crosisca** [fljot/Gestouch#44]
I'm making an Air app and decided to try Gestouch to implement my character's jump input, which is a swipe movement in the up direction.
I also have a function that uses flash TouchEvent which is used to move my character right/left based on which half of the screen you touched.
The problem that I'm having is that when I try to jump, my character also moves, is there anyway I can get the touchId of my SwipeGesture's touch, so I can ignore this touch inside my character's movement function? 

Thanks

**Comment by fljot** [comment]
You can extend SwipeGesture class and save `touch.id` in `onTouchBegin` method.

**Comment by crosisca** [comment]
Thanks, worked like a charm

**Comment by fljot** [comment]
Don't forget to perform check (not to save undesired touch):

```
if (isTrackingTouch(touch.id)) {...}
```
