### ISSUE TITLE
TapGesture with event.target.name

### ISSUE THREAD

**Issue by Mona109** [fljot/Gestouch#46]
Hello,
I have a Sprite with several buttons in it, the buttons have names that are used to create new objects. Before Gestouch I used MouseClick, so event.target.name worked fine. Now with tap it doesn't. How can event.target.name be used with the TapGesture?

**Comment by fljot** [comment]
Event is dispatched by the gesture, so `event.target is Gesture` and `event.target.target` is your Sprite, so name is `event.target.target.name` (casting is omitted).

**Comment by Mona109** [comment]
Thanks for the quick reply. I tried, but didn't work. Here what I tried:
tapStart = new TapGesture(theSprite.hisChild);
tapStart.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, startIt);  
function startIt(event:org.gestouch.events.GestureEvent):void{
    const tap:TapGesture = event.target as TapGesture;
    if (tap.target.name == "Start_01") {
        testField.text = "inside";
    }
}

**Comment by fljot** [comment]
What didn't work? You realize that `tap.target === theSprite.hisChild`, right?

**Comment by Mona109** [comment]
Yes I think so, it doesn't take the right name.
Now I made some testing, so the Tap is working, but it doesn't take the right name. when I trace the name, it is for every button "instance12". With the MouseClick it worked fine, do you have an idea whats wrong?

**Comment by fljot** [comment]
With MouseClick you probably were using event bubbling (if you talk about `event.target` instead of `event.currentTarget`).

**Comment by Mona109** [comment]
I don't really understand. 
Well now I found out that "instance12" is the Sprite where the buttons are inside. But I need to trigger the buttons. How may I get the buttons and their names with the TapGesture?

**Comment by fljot** [comment]
Option 1: attach TapGesture to every button. This way event.target.target is your button.
Option 2: attach TapGesture to buttons container, then use some sort of hit-test to get the button under `tap.location` (point in global coordinate space)

**Comment by Mona109** [comment]
Now it's fine, I tried both with success and I think Option1 would be better in my project. Thank you so much!

**Comment by fljot** [comment]
Just curious, why are you switching from MouseEvent.CLICK to Gestouch & TapGesture?

**Comment by PippoFlash** [comment]
Hi,
I have a Sprite who can successfully been panned around.
There are items within this sprite who are clickable.
It does not register any mouse event when made pannable with Gestouch.
I have tried to intercept click events but at no avail. Any hint?
cheers

**Comment by fljot** [comment]
Gestouch doesn't stop any events propagation. Everything works just fine.

```
package {

import flash.display.DisplayObject;
import flash.display.Sprite;
import flash.events.Event;
import flash.events.MouseEvent;
import flash.events.TouchEvent;

import org.gestouch.core.Gestouch;
import org.gestouch.events.GestureEvent;
import org.gestouch.extensions.native.NativeDisplayListAdapter;
import org.gestouch.extensions.native.NativeTouchHitTester;
import org.gestouch.gestures.PanGesture;
import org.gestouch.input.NativeInputAdapter;

public class Main extends Sprite {

    public function Main() {

        Gestouch.inputAdapter = new NativeInputAdapter(stage);
        Gestouch.addDisplayListAdapter(DisplayObject, new NativeDisplayListAdapter());
        Gestouch.addTouchHitTester(new NativeTouchHitTester(stage));

        var pannable:Sprite = new Sprite();
        addChild(pannable);

        var pan:PanGesture = new PanGesture(pannable);
        pan.addEventListener(GestureEvent.GESTURE_BEGAN, onPan);
        pan.addEventListener(GestureEvent.GESTURE_CHANGED, onPan);

        var child:Sprite = new Sprite();
        child.graphics.beginFill(0xCCCCCC);
        child.graphics.drawCircle(0, 0, 100);
        child.graphics.endFill();
        child.addEventListener(MouseEvent.CLICK, onChildTouch);
        child.addEventListener(TouchEvent.TOUCH_BEGIN, onChildTouch);
        child.addEventListener(TouchEvent.TOUCH_END, onChildTouch);
        pannable.addChild(child)
    }

    private function onPan(event:GestureEvent):void
    {
        trace("gesture recognized", event);
    }

    private function onChildTouch(event:Event):void
    {
        trace("child interactive event", event);
    }
}
}
```
