### ISSUE TITLE
Multiple gestures on the same target

### ISSUE THREAD

**Issue by dbathily** [fljot/Gestouch#47]
Hi,

Thank you for your framework, very helpful.

When I create 2 same gestures on the same target (tested with 2 TapGesture), only one is recognized. We should have the 2 gestures recognized.

**Comment by fljot** [comment]
Please watch those Apple videos I listed in README, they will explain you the concept of simultaneous gesture recognition.

In short use `Gesture#gesturesShouldRecognizeSimultaneouslyCallback` to allow simulnateous recognition (before this functionality was in `Gesture#delegate`).

**Comment by dbathily** [comment]
Ok, I get it. You are right, this the same behavior in iOS.

I need this for my project so I'll add this locally.

**Comment by fljot** [comment]
Ehmmmm.. sorry, what are you going to add locally?

**Comment by dbathily** [comment]
In GesturesManager i add this `!(otherTarget == target && otherGesture.reflect() == gesture.reflect()) &&` in `// conditions for otherGesture "own properties"` L167

``` as3
 if (otherGesture != gesture &&
    !(otherTarget == target && otherGesture.reflect() == gesture.reflect()) &&
    target && otherTarget &&//in case GC worked half way through
    otherGesture.enabled &&
    otherGesture.state == GestureState.POSSIBLE)
```
