### ISSUE TITLE
Can not found IGestureDelegate interface in 0.4.6

### ISSUE THREAD

**Issue by lansea** [fljot/Gestouch#49]
miss  IGestureDelegate interface in 0.4.6, how can I process the ConflictGestures?

**Comment by fljot** [comment]
I have changed `delegate` property with this interface to separate callbacks. It's better this way because you can't specify optional method to implement (like you sort of can in Objective-C).

see https://github.com/fljot/Gestouch/commit/26f459cb825d019c41fd06280e7b476bde588041

**Comment by lansea** [comment]
I try the following code to process the ConflictGestures in 0.4.6, but can not get zoom gesture function to call! it is good in 0.4.4 use delegate property.

function gestureShouldReceiveTouch(gesture:Gesture, touch:Touch):Boolean
{
    return true;
}

function gestureShouldBegin(gesture:Gesture):Boolean
{
    return true;
}

function gesturesShouldRecognizeSimultaneously(gesture:Gesture, otherGesture:Gesture):Boolean
{
    if (gesture.target == otherGesture.target)
    {
        return true;
    }

```
return false;
```

}

function gestureGcd(gesture:Gesture):void
{
    gesture.gestureShouldReceiveTouchCallback = gestureShouldReceiveTouch;

```
gesture.gestureShouldBeginCallback = gestureShouldBegin;

gesture.gesturesShouldRecognizeSimultaneouslyCallback = gesturesShouldRecognizeSimultaneously;
```

}

```
    singleTap = new TapGesture(gestureObj);
singleTap.numTapsRequired = 1;
//singleTap.delegate = gcd; 
gestureGcd(singleTap);
singleTap.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onGesture);


zoom = new ZoomGesture(gestureObj);
//zoom.delegate = gcd;
gestureGcd(zoom);
//zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onGesture);
zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onGesture);
zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onGesture);
```
