### ISSUE TITLE
How to set up in Flash CS6

### ISSUE THREAD

**Issue by yelle77** [fljot/Gestouch#54]
Hi, 

Laugh at me if you will, but I desperatly need to use your double tap function within in my IOS application but being a complete noob to coding and AS3 i have no idea how to set gestouch library up with in flash so its recognised when i write my script?

Is there a step by step instruction on the install of gestouch somewhere? 

If not can you take me through the steps of making it active in flash CS6.

Thank you.

**Comment by thomaspaillot** [comment]
Hi,

Download the source and copy the "org" folder in the same folder than your .fla file. That's it, now you can use the example provided in the README file.

**Comment by yelle77** [comment]
Thats exactly what i did but when testing i keep getting errors such as 

Scene 1, Layer 'actions', Frame 1, Line 45  1180: Call to a possibly undefined method TapGesture.
Scene 1, Layer 'actions', Frame 1, Line 45  1046: Type was not found or was not a compile-time constant: TapGesture.

My code reads

...

var doubleTap:TapGesture = new TapGesture(spinX_mc);
doubleTap.numTapsRequired = 2;
doubleTap.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onDoubleTap);

function onDoubleTap(event:org.gestouch.events.GestureEvent):void
{
    if (spinX_mc.scaleX == 2 && spinX_mc.visible == true)
    {
        spinX_mc.scaleX *= 1;
        spinX_mc.scaleY *= 1;
    }
    else
    {
        spinX_mc.scaleX *= 2;
        spinX_mc.scaleY *= 2
    }
}

**Comment by thomaspaillot** [comment]
You have to import classes you use in the beginning of your file, like this :

import org.gestouch.gestures.TapGestures;
import org.gestouch.events.GestureEvent;

**Comment by yelle77** [comment]
Scene 1, Layer 'actions', Frame 1, Line 70  1180: Call to a possibly undefined method TapGesture.
Scene 1, Layer 'actions', Frame 1, Line 17  1172: Definition org.gestouch.gestures:TapGestures could not be found.
Scene 1, Layer 'actions', Frame 1, Line 70  1180: Call to a possibly undefined method TapGesture.

 Now i get this? ...ummm may have to think of another solution as on a tight deadline.

**Comment by thomaspaillot** [comment]
Maybe like this,

doubleTap.addEventListener(GestureEvent.GESTURE_RECOGNIZED, onDoubleTap);

function onDoubleTap(event:GestureEvent):void { }

**Comment by jamesmfoley** [comment]
I get the same thing If I look through the class files I find no record of GESTURE_RECOGNIZED

**Comment by ghost** [comment]
Here is what I did. Created a button instance called my button and a dynamic text field called display.

Imported all the classes.

Put the full path to the gesture recognized event.

Not sure why I have to put the full path to the event. If any one can explain this it would be helpful to my learning.
import org.gestouch.core.\* 
import org.gestouch.events.GestureEvent;
import org.gestouch.extensions._;
import org.gestouch.gestures._;
import org.gestouch.input.*
import org.gestouch.utils.*

var doubleTap:TapGesture = new TapGesture(myButton);
doubleTap.numTapsRequired = 2;
doubleTap.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onDoubleTap);

 function onDoubleTap(e:GestureEvent):void
{
    display.text = "double tap: " + e;
}

**Comment by jamesmfoley** [comment]
Here is what I did to get it working

import org.gestouch.core.* 
import org.gestouch.events.GestureEvent;
import org.gestouch.extensions.*;
import org.gestouch.gestures.*;
import org.gestouch.input.*
import org.gestouch.utils.*



var doubleTap:TapGesture = new TapGesture(myButton);
doubleTap.numTapsRequired = 2;
doubleTap.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onDoubleTap);
 
 function onDoubleTap(e:GestureEvent):void
{
	display.text = "double tap: " + e;
}

**Comment by fljot** [comment]
@jamesmfoley 
Code on the frame? Because Flash has some shortcut to flash.events.GestureEvent and it confuses it with the actual class that you write import for. Same for MXML. Some native classes racism.

**Comment by ghost** [comment]
?I know I am lazy. I went through all the event and made example with Flash CS 6 if anyone would like them they all work. Will Adobe ever give access to Native Gesture and Touch Events?

Jim

**Comment by tonybot3** [comment]
james, may i see what you did for pinch zoom gesture? thank you
