### ISSUE TITLE
Hover event

### ISSUE THREAD

**Issue by ramezrafla** [fljot/Gestouch#56]
Pavel, this library is nothing short of fantastic!
Well done!

This is a feature request that you can safely ignore if you don't want :)

How hard is it to add hover events for Flash (i.e. desktop)?

**Comment by fljot** [comment]
@ramezrafla thanks. And what do you mean by hover events in touch gestures context?

**Comment by ramezrafla** [comment]
I mean when the mouse is over (MouseEvent.OVER). Not really gestures - I am using gestouch with Starling and need to handle OVER events manually as an exception to gestouch. Not a big deal - just wondering. If we develop HoverGesture I could share it, but it will be starling-specific.

**Comment by fljot** [comment]
@ramezrafla and what's wrong with just listening to those Starling "touch hover" events?

**Comment by ramezrafla** [comment]
Nothing - I would have rathered have consistency in code.
Not a big deal. Thanks!

## 

Ramez Rafla
President
/ZeGenie.com/
(m) 514.978.8198
(e) ramez@zegenie.com
(w) www.zegenie.com
(in)ca.linked.com/in/ramezrafla  http://ca.linkedin.com/in/ramezrafla
(cal)google.com/calendar  https://www.google.com/calendar/embed?src=ramez%40zegenie.com
