### ISSUE TITLE
Away3D

### ISSUE THREAD

**Issue by ramezrafla** [fljot/Gestouch#57]
Hi again Pavel,

You mentioned in one of the posts that Away3D can be supported. Is that out-of-the-box or are there additional libraries to use?

If the project is still in its infancy, don't mind taking it over (with some guidance :)

Thanks a lot Pavel!

**Comment by fljot** [comment]
@ramezrafla please read here http://forum.starling-framework.org/topic/gestouch-%E2%80%94-multitouch-gestures-for-starling-and-classic-displaylist/page/3
To summarize — can be done, but noone has submitted solution to include it right away (like I did for Starling).

**Comment by ramezrafla** [comment]
Thanks Pavel.

Makes sense. Probably because people rarely need complex gestures with away3d, touch and drag are the most common. And away3d has the libraries for that.

**Comment by fljot** [comment]
Oh could you point to those please?

**Comment by carlosg2** [comment]
Some references:
https://github.com/ideum/gestureworks-flash-away3d/tree/master/com/gestureworks/away3d
