### ISSUE TITLE
Pure Flash Example

### ISSUE THREAD

**Issue by mhmttosun** [fljot/Gestouch#6]
Hi,
Your works are really well done. What i asked for is that are there any flash version of  example project. I think there ara many people do not use Flex. There many users who uses Air For Android or Air for iOS. Can you provide a Flash/as3 version of example project.
Thanks.

**Comment by fljot** [comment]
What's exactly wrong with the current examples project? Flex is used there just for a quick UI (list of examples and its selection). Build is IDE-independent and platform-independent (as powered by Ant), so all you need is Flex SDK + AIR SDK, Ant and command line.
