### ISSUE TITLE
Problem with gestouch when compil trought a ANT script

### ISSUE THREAD

**Issue by christalys** [fljot/Gestouch#65]
Hi,

we use gestouch on an Starling mobile project in AIR 4.0. Our IDE is inteliji. It work very well.
But we've got a problem when compiling our app with ANT. Gestouch gesture are not recognize....

Any idea ?

**Comment by fljot** [comment]
Well I see no possible way gesture **recognition** would depend on the way you build it. There must be runtime error, I guess, and you can see it.

**Comment by christalys** [comment]
Resolved ! 
We remove the " -useLegacyAOT no " parameter...and it works.
