### ISSUE TITLE
Smooth Scrolling of Sprite

### ISSUE THREAD

**Issue by cbrunstetter** [fljot/Gestouch#73]
I am trying to implement iOS like scrolling to a sprite that contains many images (exactly like iOS Photos App). The path I am going down is to use Swipe, like a flick (tween up/down so many pixels) and a Pan (drag up/down). Can these be used in combination? Is there an easier way to implement iOS native scrolling?

Thanks!

**Comment by fljot** [comment]
@cbrunstetter use pan only, swipe is not helpful for this case.

https://github.com/fljot/TouchScrolling/blob/features/decoupled-architecture/src/com/inreflected/ui/touchScroll/TouchScrollModel.as

**Comment by cbrunstetter** [comment]
Excellent, thank you for the response. I'll give it a shot.
