### ISSUE TITLE
Pan and Zoom same time - two areas

### ISSUE THREAD

**Issue by dmen** [fljot/Gestouch#78]
I cannot get this to work - and I have to for a project I am doing - it is for multiple people to use the same touch screen at the same time. Right now, for testing, I have two touch areas - sprites. One uses a TransformGesture so I can pan and scale a 3D object at the same time. The other uses a PanGesture so I can move a sprite around. Two people can pan at the same time without problem. But if the second area is being touched in then the pinch-zoom fails to work at all. Only when the second area is not being touched in can I zoom in the first. 
Doing this in AS3. Saw something about only two touch points being supported? Which would make some sense, because zooming and panning require three.

**Comment by fljot** [comment]
@dmen let's start from the beginning – what's the runtime & hardware capabilities? Try checking `flash.ui.Multitouch#maxTouchPoints` and just to be sure

```
Multitouch.inputMode = MultitouchInputMode.TOUCH_POINT;
stage.addEventListener(TouchEvent.TOUCH_BEGIN, function(e:TouchEvent):void{
    trace("Touch begin", e.touchPointID);
});
```

and touch it with as many fingers as you have – you will see the max you can get.

**Comment by dmen** [comment]
Thanks for replying Pavel. Sorry I didn't do such a simple test prior.

Runtime is AIR for desktop, from Flash CS6. Windows 8 Enterprise. 

So - all of those can do more than two touch points... so it must be my monitor? HP Compaq L2105tm. 
Seems so. Did a quick search and found a comment on amazon.com: "First, "multi" only means more than one. As in two. This monitor only accepts two touches total."

So. If I get a better monitor - should I be able to do what I'm looking for? Thanks!

**Comment by fljot** [comment]
@dmen of course you should be able to)
