### ISSUE TITLE
Gestouch interrupts websocket

### ISSUE THREAD

**Issue by nafem** [fljot/Gestouch#79]
I am using worlize websocket but when I load Gestouch the websocket closes silently. 

I have looked through the code but can't see anywhere that sockets are implemented in Gestouch. Any ideas where Gestouch may be interfering with the socket?

**Comment by fljot** [comment]
O.o
no, no sockets whatsoever. No idea what's happening =/
Try compiling against latest sources maybe? I've removed "mushroom operator" at least.

**Comment by nafem** [comment]
Forget this, I tested this a lot before asking but it seems that it was a LAN issue rather than anything to do with Gestouch.

Thanks for replying though, and for your great work.
