### ISSUE TITLE
flash cc simple test problem

### ISSUE THREAD

**Issue by bluelemonade** [fljot/Gestouch#81]
hello,

I've done I smll test clip with to image clips. image_mc and image2_mc. I am testing on a dell multitouch notebook with windows 8.1

when I use the freetransform event, I can move one clip around, but I can not move booth clips at the ame time. where is my fault? although zoom and rotation didn't work, or this a hardware issue?

regards.

```
import flash.display.MovieClip;
import flash.events.Event;
import flash.geom.Matrix;
import flash.utils.*

import org.gestouch.core.Gestouch;
import org.gestouch.events.GestureEvent;
import org.gestouch.input.NativeInputAdapter;
// import org.gestouch.gestures.TapGesture;
import org.gestouch.gestures.TransformGesture;
// import org.gestouch.gestures.ZoomGesture;
// import org.gestouch.gestures.SwipeGesture;



public class mtouchGesture extends MovieClip
{

    var twoFingerTapStageSize = 0.5;
    var twoFingerTapImageSize = 0.5;

    // var zoom:ZoomGesture;
    // var doubleTap:TapGesture;
    // var freeTransform:TransformGesture;
    // var freeTransform2:TransformGesture;

    function mtouchGesture()
    {

        super();
        Gestouch.inputAdapter = new NativeInputAdapter(this.stage);
        this.addEventListener(Event.ADDED_TO_STAGE, onATS, false,0, true);

    }


    function onATS(evt: Event):void
    {

        initImage();

    }



     /* function onStageTap(event: org.gestouch.events.GestureEvent):void
    {

        trace("onStageTap");
        //const gesture: ZoomGesture = event.target as TabGesture;
    } */





    // var freeTransform:TransformGesture;
    function initImage()
    {

        // myCmnFx.swapToFront(loader_mc);
        image_mc.scaleX = 0.5;
        image_mc.scaleY = 0.5;

        // image_mc.x = Math.random() * stage.stageWidth -(stage.stageWidth*0.2);
        // image_mc.y = Math.random() * stage.stageHeight -(stage.stageHeight*0.2);
        // quadrat.cacheAsBitmap=true;

        // image_mc.rotation = (Math.random() * 20) - 10;

        /*
        doubleTap = new TapGesture(image_mc);
        doubleTap.maxTapDistance = 800;
        doubleTap.numTapsRequired = 2;
        doubleTap.addEventListener(org.gestouch.events.GestureEvent.GESTURE_RECOGNIZED, onDoubleTap);
        */

        //doubleTap.addEventListener(org.gestouch.events.GestureEvent.G, onDoubleTap);

        // var freeTransform:TransformGesture = new TransformGesture(quadrat);

        var freeTransform:TransformGesture = new TransformGesture(image_mc);
        freeTransform.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onFreeTransform);
        freeTransform.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onFreeTransform);

        var freeTransform2:TransformGesture = new TransformGesture(image2_mc);
        freeTransform2.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onFreeTransform);
        freeTransform2.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onFreeTransform);

        // mc.x = -600;
        // mc.y = -450;
        // quadrat.addChild(mc);

        /*
        zoom = new ZoomGesture(image_mc);
        zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_BEGAN, onGestureZoom);
        zoom.addEventListener(org.gestouch.events.GestureEvent.GESTURE_CHANGED, onGestureZoom);
        */



    }

    private function onFreeTransform(event:org.gestouch.events.GestureEvent):void

    {

        trace(event.target.target.name + getTimer() );

        var theX:int = event.target.target.x;
        var theY:int = event.target.target.y;

        // freeTransform = event.target as TransformGesture;

        // var freeTransformClip:MovieClip = event.target as MovieClip
        // move, rotate, scale — all at once for better performance!
        // trace(event.target.offsetX, event.target.offsetY, event.target.rotation, event.target.scale);
        // trace(freeTransform.offsetX, freeTransform.offsetY, freeTransform.rotation, freeTransform.scale);


        event.target.target.x = theX +event.target.offsetX;
        event.target.target.y = theY +event.target.offsetY;
        event.target.target.rotation = event.target.rotation;
        event.target.target.scale = event.target.scale;

    }



     function onGestureZoom(event: org.gestouch.events.GestureEvent):void
    {

            trace("onGestureZoom");
            //const gesture:ZoomGesture = event.target as ZoomGesture;

            /*
            var matrix: Matrix = zoomall.transform.matrix;
            var transformPoint: Point = matrix.transformPoint(zoomall.globalToLocal(zoom.location));
            matrix.translate(-transformPoint.x, -transformPoint.y);
            matrix.scale(gesture.scaleX, gesture.scaleY);
            matrix.translate(transformPoint.x, transformPoint.y);
            zoomall.transform.matrix = matrix;
            //*/


    }



    private function onDoubleTap(event:org.gestouch.events.GestureEvent):void
    {
        // handle double tap!
        trace("doubletap");
    }
}
```

**Comment by fljot** [comment]
I don't know, try to test with TouchEvents – how many can you get at the same time.

**Comment by bluelemonade** [comment]
10! the rotation and zoom work fine with the native adbe events.

**Comment by fljot** [comment]
Compile against sources with CONFIG::GestouchDebug set to true and check the logging.
Also, setting input adapter might be unnecessary (if you set any, you actually should dispose existing one).

**Comment by bluelemonade** [comment]
thanks, where is the logging?

**Comment by fljot** [comment]
You will see this output
https://github.com/fljot/Gestouch/commit/7d929b23b6482e2448ef18ab412d27fae4c2a325
if you compile with `-define+=CONFIG::GestouchDebug,false`
(see recent commits for more details if needed)

**Comment by bluelemonade** [comment]
ok, now I swtich to flashbuilder 4.6, an added -define+=CONFIG::GestouchDebug,true in the flash compiler settings.

I can drag to images at the same time, but no output, no zooming.

**Comment by fljot** [comment]
There should be traces if you compile against the recent sources from the develop branch, cmon man.

**Comment by bluelemonade** [comment]
here i am:

i compiled for air 16.0, I can move a couple of images at the same time. 

[Gestouch] org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchMove() Touch move: Touch [id: 399, location: (x=407, y=494), target: [object MovieClip], time: 7049]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=407 localY=494 stageX=407 stageY=494 sizeX=3.7834502501539417e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=3.783477800802789e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=3.783477800802789e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=399 isPrimaryTouchPoint=false localX=406 localY=495 stageX=406 stageY=495 sizeX=3.783477800802789e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchMove() Touch move: Touch [id: 399, location: (x=406, y=495), target: [object MovieClip], time: 7063]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=406 localY=495 stageX=406 stageY=495 sizeX=3.783477800802789e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=1.3941905179943759e-38 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=1.3941905179943759e-38 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=399 isPrimaryTouchPoint=false localX=405 localY=496 stageX=405 stageY=496 sizeX=1.3941905179943759e-38 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchMove() Touch move: Touch [id: 399, location: (x=405, y=496), target: [object MovieClip], time: 7071]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=405 localY=496 stageX=405 stageY=496 sizeX=1.3941905179943759e-38 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=3.7834226995050943e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=3.7834226995050943e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=399 isPrimaryTouchPoint=false localX=403 localY=497 stageX=403 stageY=497 sizeX=3.7834226995050943e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchMove() Touch move: Touch [id: 399, location: (x=403, y=497), target: [object MovieClip], time: 7083]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=403 localY=497 stageX=403 stageY=497 sizeX=3.7834226995050943e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchEndHandler() Touch end/cancel via touch event: [TouchEvent type="touchEnd" bubbles=true cancelable=false eventPhase=1 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=3.783491576127213e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchCancel() Touch begin: Touch [id: 398, location: (x=807, y=361), target: [object MovieClip], time: 7037]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchEndHandler() Touch end/cancel via touch event: [TouchEvent type="touchEnd" bubbles=true cancelable=false eventPhase=2 touchPointID=398 isPrimaryTouchPoint=true localX=807 localY=361 stageX=807 stageY=361 sizeX=3.783491576127213e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=1 touchPointID=399 isPrimaryTouchPoint=false localX=403 localY=497 stageX=403 stageY=497 sizeX=3.783491576127213e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchMoveHandler() Touch move via touch event: [TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=403 localY=497 stageX=403 stageY=497 sizeX=3.783491576127213e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchEndHandler() Touch end/cancel via touch event: [TouchEvent type="touchEnd" bubbles=true cancelable=false eventPhase=1 touchPointID=399 isPrimaryTouchPoint=false localX=403 localY=497 stageX=403 stageY=497 sizeX=1.3941905179943759e-38 sizeY=0 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=1034870698 touchIntent="pen" isTouchPointCanceled=false]
[Gestouch] org.gestouch.core::TouchesManager/org.gestouch.core::gestouch_internal::onTouchEnd() Touch end: Touch [id: 399, location: (x=403, y=497), target: [object MovieClip], time: 7083]
[Gestouch] org.gestouch.input::NativeInputAdapter/touchEndHandler() Touch end/cancel via touch event: [TouchEvent type="touchEnd" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=403 localY=497 stageX=403 stageY=497 sizeX=1.3941905179943759e-38 sizeY=0 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=1034870698 touchIntent="pen" isTouchPointCanceled=false]

**Comment by bluelemonade** [comment]
ok, what can I see in this output?

**Comment by fljot** [comment]
Well it's all written – what can you see?)
I can see that
1) this log starts NOT from the beginning of the interaction sequence
2)

```
[TouchEvent type="touchMove" bubbles=true cancelable=false eventPhase=2 touchPointID=399 isPrimaryTouchPoint=false localX=407 localY=494 stageX=407 stageY=494 sizeX=3.7834502501539417e-35 sizeY=2.5123676378994732e-29 pressure=1 relatedObject=null ctrlKey=false altKey=false shiftKey=false commandKey=false controlKey=false timestamp=4186980266 touchIntent="pen" isTouchPointCanceled=true]
```

Runtime gives you `isTouchPointCanceled=true` in touch move, while [documentation says](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/TouchEvent.html#isTouchPointCanceled) "isTouchPointCanceled can only be true in a touchEnd event".

So the only thing that is clear for now is that runtime is buggy as usual :/

**Comment by bluelemonade** [comment]
thanks its working now. I set although themouseflag, so I can use the app with the mouse. very nice implementation.

**Comment by fljot** [comment]
Sorry, what did you do again?
