### ISSUE TITLE
Gestures doesn't work with MultiTouch screen on Windows

### ISSUE THREAD

**Issue by steven1152** [fljot/Gestouch#83]
Hi,

I can't make gesture work on any pc with a multitouch screen.
Nothing seems to work if a multitouch screen is detected, even what usually works with the mouse does not work if a multi touch screen is connected when I start flash player.
Connecting the usb cable from the screen after starting flash works, the gestures from the screen works like they do with the mouse.
Here are a few things I tried that did not work:
-Setting Multitouch.inputMode to "none"
-Setting Multitouch.mapTouchToMouse to true
-Different browsers (All browser that have Multitouch.supportsGestureEvents==true does not work)

Here is a test project that has the problem:
https://drive.google.com/file/d/0B7owVyT9RqyaVnlpVWZ3LXR4MmM/view?usp=sharing

Any idea of what I could try?

Thanks,

**Comment by fljot** [comment]
Try to get some debug traces regarding input first (see here https://github.com/fljot/Gestouch/issues/81)

**Comment by steven1152** [comment]
Here are the only two lines I get on the touchscreen:
"[Gestouch] org.gestouch.input::NativeInputAdapter/init() Multitouch.supportsTouchEvents: true" 
"[Gestouch] org.gestouch.input::NativeInputAdapter/init() _explicitlyHandleTouchEvents: false"

And I get nothing when I click or touch the screen.
If I try the same .swf on another computer I get a lot of log when I click anywhere.

**Comment by fljot** [comment]
Looks like you don't receive flash TouchEvent-s.
Try to handle some touch events manually, confirm that you don't get them. And then try to understand why you don't get them)
Gestouch (by default) uses native touch or/and mouse events from the runtime.. nothing magical.

**Comment by steven1152** [comment]
Thanks, I was indeed not receiving touchEvents.
I add this to the beginning of the application:
Multitouch.inputMode = MultitouchInputMode.TOUCH_POINT;

and changed the wmode in the html page from "transparent" to "direct".

Now everything works from the touch screen but not the mouse. (I don't really care if the mouse doesn't work.)

I just did not expect mouse support to stop working if a touch screen is detected.

**Comment by fljot** [comment]
Multitouch.inputMode should be set to TOUCH_POINT by Gestouch.

And you can actually use touch and mouse together, see NativeInputAdapter.
